name: Trivy IaC Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  trivy-scan:
    name: Run Trivy on Terraform Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          format: table
          exit-code: 1
